import type { Metadata } from "next";
import "./globals.css";

import { Montserrat, Oxanium } from "next/font/google";

const oxanium = Oxanium({
	weight: ["500", "600"],
	variable: "--font-oxanium",
	subsets: ["latin"],
});

const montserrat = Montserrat({
	weight: ["400", "600"],
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={` ${oxanium.variable} ${montserrat.variable}`}>
			<body className="bg-gray-900 text-gray-100 antialiased bg-[url(/background.png)] bg-no-repeat md:bg-right-top bg-top">
			<main className="max-w-[1240px] mx-auto px-5 py-8 md:py-0">
          {children}
        </main>
			</body>
		</html>
	);
}
